spring:
  application:
    name: order-service
  datasource:
    url: { url }
    username: { username }
    password: { password }
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false

server:
  port: { server-port }
eureka:
  client:
    service-url:
      defaultZone: { msa server url }

management:
  zipkin:
    tracing:
      endpoint: { entry zipkin info }
  tracing:
    sampling:
      probability: 1.0